{{ if .Values.ingress.enabled }}
# apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "gateway.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: "{{ $val }}"
{{- end }}
spec:
{{ if .Values.ingress.tls }}
  tls:
  {{ if .Values.ingress.secretName }}
  - secretName: {{.Values.ingress.secretName}}
  {{ end }}
  - hosts:
  {{if .Values.ingress.hostname }}
    - {{ .Values.ingress.hostname }}
  {{ else }}
    - {{ .Values.clusterHostname }}
  {{ end }}
{{ end }}
  rules:
  {{if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
  {{ else }}
  - host: {{ .Values.clusterHostname }}
  {{ end }}
    http:
      paths:
      - backend:
          serviceName: {{ template "gateway.fullname" . }}
          servicePort: {{ .Values.ingress.port }}
  {{if .Values.ingress.additionalHostnamesAndPorts }}
  {{- $gatewayFullName := include "gateway.fullname" . }}
  {{- range $key, $val := .Values.ingress.additionalHostnamesAndPorts }}
  - host: {{ $key }}
    http:
      paths:
      - backend:
          serviceName: {{ $gatewayFullName }}
          servicePort: {{ $val }}
  {{- end }}
  {{ end }}
{{ end }}
